# Generated by Django 3.2.7 on 2021-11-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repetionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnom', models.CharField(max_length=50)),
                ('cemail', models.EmailField(max_length=50)),
                ('cquartier', models.CharField(max_length=100)),
                ('cclasse', models.CharField(max_length=50)),
                ('cpmatiere', models.CharField(max_length=60)),
                ('cdmatiere', models.CharField(max_length=60)),
                ('cmessage', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
    ]
