# Generated by Django 3.2.7 on 2021-11-11 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repetionApp', '0002_auto_20211110_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='cclasse',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cdmatiere',
        ),
        migrations.RemoveField(
            model_name='client',
            name='cpmatiere',
        ),
    ]
